import { dateLabel } from "@/lib/format";

const link = "inline-flex min-h-11 items-center transition-colors hover:text-white";

export function Footer({ generatedAt, source }: { generatedAt?: string; source?: string }) {
  return (
    <footer className="w-full bg-black px-4 pb-10 pt-14 text-white md:px-16 lg:px-24">
      <div className="mx-auto grid max-w-6xl gap-10 md:grid-cols-[1.4fr_1fr]">
        <div>
          <div className="flex items-center gap-2.5">
            <span className="grid size-8 place-items-center rounded-full bg-white text-xs font-bold text-zinc-950">R</span>
            <span className="text-sm font-semibold">R Programming and Data Web Extraction</span>
          </div>
          <p className="mt-4 max-w-md text-sm leading-6 text-zinc-400">
            An interactive presentation of the R practical exam. Every number, table and figure on this page is read from files generated by{" "}
            <code className="text-zinc-300">main_analysis.R</code>; the R analysis remains the source of truth.
          </p>
        </div>
        <nav aria-label="Footer" className="grid grid-cols-2 gap-6 text-sm text-zinc-400">
          <div className="flex flex-col">
            <span className="mb-1 text-sm text-white">Explore</span>
            <a href="#figures" className={link}>Required figures</a>
            <a href="#relationship" className={link}>Analysis</a>
            <a href="#explorer" className={link}>Country explorer</a>
            <a href="#quality" className={link}>Data quality</a>
          </div>
          <div className="flex flex-col">
            <span className="mb-1 text-sm text-white">Outputs</span>
            <a href="/project/final_report.pdf" target="_blank" rel="noreferrer" className={link}>Final report (PDF)</a>
            <a href="/project/cleaned_data.csv" download className={link}>cleaned_data.csv</a>
            <a href="/project/data_dictionary.csv" download className={link}>data_dictionary.csv</a>
            <a href="/project/analysis_summary.json" target="_blank" rel="noreferrer" className={link}>analysis_summary.json</a>
          </div>
        </nav>
      </div>
      <div className="mx-auto mt-10 flex max-w-6xl flex-col gap-2 border-t border-white/10 pt-6 text-xs text-zinc-400 md:flex-row md:justify-between">
        <span>
          Data:{" "}
          <a href="https://data.worldbank.org" target="_blank" rel="noreferrer" className="underline hover:text-white">
            {source ?? "World Bank World Development Indicators"}
          </a>
        </span>
        {generatedAt && <span>Outputs generated {dateLabel(generatedAt)}</span>}
      </div>
    </footer>
  );
}
