import { dateLabel } from "@/lib/format";

export function Footer({ generatedAt, source, sourceUrl }: { generatedAt?: string; source?: string; sourceUrl?: string }) {
  return (
    <footer className="w-full bg-black px-4 pb-10 pt-14 text-white md:px-16 lg:px-24">
      <div className="mx-auto grid max-w-6xl gap-10 md:grid-cols-[1.4fr_1fr]">
        <div>
          <div className="flex items-center gap-2.5">
            <span className="grid size-8 place-items-center rounded-full bg-white text-xs font-bold text-zinc-950">R</span>
            <span className="text-sm font-semibold">R Programming and Data Web Extraction</span>
          </div>
          <p className="mt-4 max-w-md text-sm leading-6 text-zinc-400">
            Interactive presentation layer for the R practical exam. Every number, table and figure on this page is read from files
            generated by <code className="text-zinc-300">main_analysis.R</code>; the R analysis remains the source of truth.
          </p>
        </div>
        <div className="grid grid-cols-2 gap-6 text-xs text-zinc-400">
          <div className="flex flex-col gap-2.5">
            <span className="text-sm text-white">Explore</span>
            <a href="#figures" className="hover:text-white">Required figures</a>
            <a href="#analysis" className="hover:text-white">Advanced analysis</a>
            <a href="#explorer" className="hover:text-white">Country explorer</a>
            <a href="#quality" className="hover:text-white">Data quality</a>
          </div>
          <div className="flex flex-col gap-2.5">
            <span className="text-sm text-white">Outputs</span>
            <a href="/project/final_report.pdf" target="_blank" rel="noreferrer" className="hover:text-white">Final report (PDF)</a>
            <a href="/project/cleaned_data.csv" download className="hover:text-white">cleaned_data.csv</a>
            <a href="/project/data_dictionary.csv" download className="hover:text-white">data_dictionary.csv</a>
            <a href="/project/analysis_summary.json" target="_blank" rel="noreferrer" className="hover:text-white">analysis_summary.json</a>
          </div>
        </div>
      </div>
      <div className="mx-auto mt-12 flex max-w-6xl flex-col gap-2 border-t border-white/10 pt-6 text-xs text-zinc-500 md:flex-row md:justify-between">
        <span>
          Data:{" "}
          {sourceUrl ? (
            <a href="https://data.worldbank.org" target="_blank" rel="noreferrer" className="underline hover:text-zinc-300">
              {source ?? "World Bank World Development Indicators"}
            </a>
          ) : (
            "World Bank World Development Indicators"
          )}
        </span>
        {generatedAt && <span>Outputs generated {dateLabel(generatedAt)}</span>}
      </div>
    </footer>
  );
}
