import { Reveal } from "@/components/motion/primitives";
import { Section, SectionHeading } from "@/components/ui";
import type { AnalysisSummary } from "@/lib/project-data";

/** Scene 13. Deliberately calm: opacity-only reveals, no movement. Text is generated by R. */
export function Limitations({ limitations }: { limitations: AnalysisSummary["limitations"] }) {
  return (
    <Section id="limitations" tone="dark" labelledBy="limitations-title">
      <SectionHeading
        id="limitations-title"
        dark
        scene="13"
        eyebrow="LIMITATIONS"
        title="What these results can and cannot show"
        intro="Generated by R alongside the results, so the counts and countries below match this run. The same text appears in the final report."
      />
      <ol className="mt-14 grid gap-px overflow-hidden rounded-2xl bg-white/10 md:grid-cols-2">
        {limitations.map((l, i) => (
          <Reveal as="li" key={l.title} variant="fade" delay={Math.min(i * 0.08, 0.4)} className="bg-zinc-950 p-6 md:p-8">
            <p className="text-xs tabular-nums text-zinc-400">{String(i + 1).padStart(2, "0")}</p>
            <h3 className="mt-2 text-lg font-semibold text-white">{l.title}</h3>
            <p className="mt-2 text-sm leading-6 text-zinc-300">{l.text}</p>
          </Reveal>
        ))}
      </ol>
    </Section>
  );
}
