import { Reveal } from "@/components/reveal";
import { Section, SectionHeading } from "@/components/ui";
import type { AnalysisSummary } from "@/lib/project-data";

export function Limitations({ limitations }: { limitations: AnalysisSummary["limitations"] }) {
  return (
    <Section id="limitations" tone="dark">
      <SectionHeading
        dark
        eyebrow="LIMITATIONS"
        title="What these results can and cannot show"
        intro="Generated by R alongside the results, so the counts and countries below match this run. The same text appears in the final report."
      />
      <div className="mt-12 grid gap-3 md:grid-cols-2">
        {limitations.map((l, i) => (
          <Reveal key={l.title} delay={(i % 2) * 0.04}>
            <div className="h-full rounded-2xl border border-white/10 bg-white/[0.03] p-5">
              <div className="text-xs tabular-nums text-zinc-500">{String(i + 1).padStart(2, "0")}</div>
              <h3 className="mt-2 text-base font-semibold text-white">{l.title}</h3>
              <p className="mt-2 text-sm leading-6 text-zinc-400">{l.text}</p>
            </div>
          </Reveal>
        ))}
      </div>
    </Section>
  );
}
