import { Footer } from "@/components/footer";
import { Navbar } from "@/components/navbar";
import { loadProjectData } from "@/lib/project-data";
import { AdvancedAnalysis } from "@/sections/advanced-analysis";
import { CountryExplorer } from "@/sections/country-explorer";
import { DataQuality } from "@/sections/data-quality";
import { Figures } from "@/sections/figures";
import { Hero } from "@/sections/hero";
import { KeyIndicators } from "@/sections/key-indicators";
import { Limitations } from "@/sections/limitations";
import { Methodology } from "@/sections/methodology";
import { Pipeline } from "@/sections/pipeline";
import { Reproducibility } from "@/sections/reproducibility";
import { prettyVariable } from "@/lib/format";

// Read the R outputs on every request, so re-running the R analysis updates the
// dashboard without rebuilding it.
export const dynamic = "force-dynamic";

export default async function Home() {
  const result = await loadProjectData();

  if (!result.ok) {
    return (
      <main className="grid min-h-screen place-items-center bg-zinc-50 px-4">
        <div className="max-w-xl rounded-2xl border border-red-200 bg-white p-8">
          <div className="text-xs font-semibold tracking-[0.16em] text-red-700">DATA NOT AVAILABLE</div>
          <h1 className="mt-2 text-2xl font-semibold text-zinc-950">The dashboard could not load the R analysis outputs</h1>
          <p className="mt-3 text-sm leading-6 text-zinc-600">
            This page only displays results generated by the R project, so it shows nothing rather than invented numbers.
          </p>
          <ul className="mt-4 list-disc space-y-2 pl-5 text-sm text-zinc-700">
            {result.problems.map((p) => <li key={p}>{p}</li>)}
          </ul>
          <p className="mt-5 text-sm text-zinc-600">
            Fix: open a terminal in the project folder and run <code className="rounded bg-zinc-100 px-1.5 py-0.5">Rscript build_report.R</code>, then reload this page.
          </p>
        </div>
      </main>
    );
  }

  const { data } = result;
  const { summary } = data;

  // Flags for the explorer come straight from R's outlier and regression-diagnostic results.
  const outlierFlags: Record<string, string[]> = {};
  for (const v of summary.outliers.variables) {
    for (const c of v.countries) (outlierFlags[c.country] ??= []).push(prettyVariable(v.variable));
  }

  return (
    <>
      <Navbar reportAvailable={data.reportAvailable} />
      <main>
        <Hero data={data} />
        <Pipeline data={data} />
        <KeyIndicators data={data} />
        <Figures figures={summary.figures} version={data.version} />
        <AdvancedAnalysis summary={summary} />
        <CountryExplorer
          countries={data.countries}
          regions={summary.group_analysis.by_region.map((r) => r.region).sort()}
          incomeLevels={summary.group_analysis.by_income.map((r) => r.income_level)}
          outlierFlags={outlierFlags}
          influential={summary.regression.diagnostics.influential.map((i) => i.country)}
        />
        <DataQuality qa={data.qa} />
        <Methodology summary={summary} manifest={data.manifest} />
        <Limitations limitations={summary.limitations} />
        <Reproducibility summary={summary} manifest={data.manifest} reportAvailable={data.reportAvailable} />
      </main>
      <Footer generatedAt={summary.generated_at} source={summary.project.source} sourceUrl={summary.project.source_url} />
    </>
  );
}
