import { ChapterNav } from "@/components/chapter-nav";
import { Footer } from "@/components/footer";
import { assetUrl, loadProjectDataOrThrow } from "@/lib/project-data";
import { prettyVariable } from "@/lib/format";
import { Closing } from "@/sections/closing";
import { CountryExplorer } from "@/sections/country-explorer";
import { DataQuality } from "@/sections/data-quality";
import { Figures, type FigureChapter } from "@/sections/figures";
import { Groups } from "@/sections/groups";
import { Hero } from "@/sections/hero";
import { KeyIndicators } from "@/sections/key-indicators";
import { Limitations } from "@/sections/limitations";
import { Methodology } from "@/sections/methodology";
import { Pipeline } from "@/sections/pipeline";
import { Relationship } from "@/sections/relationship";
import { Reproducibility } from "@/sections/reproducibility";
import { Robustness } from "@/sections/robustness";
import { SectionA } from "@/sections/section-a";
import { ShortAnswer } from "@/sections/short-answer";

// Rendered once at build time from the R outputs in public/project: the deployed
// site is static HTML + JSON/PNG/PDF and never needs R. Re-run R, then rebuild.
export const dynamic = "force-static";

export default async function Home() {
  const result = await loadProjectDataOrThrow();

  if (!result.ok) {
    // Development only: production builds fail loudly instead (see loadProjectDataOrThrow)
    return (
      <main className="grid min-h-screen place-items-center bg-zinc-50 px-4">
        <div className="max-w-xl rounded-2xl border border-red-200 bg-white p-8">
          <div className="text-xs font-semibold tracking-[0.16em] text-red-700">DATA NOT AVAILABLE</div>
          <h1 className="mt-2 text-2xl font-semibold text-zinc-950">The site could not load the R analysis outputs</h1>
          <p className="mt-3 text-sm leading-6 text-zinc-600">
            This page only displays results generated by the R project, so it shows nothing rather than invented numbers.
          </p>
          <ul className="mt-4 list-disc space-y-2 pl-5 text-sm text-zinc-700">
            {result.problems.map((p) => <li key={p}>{p}</li>)}
          </ul>
          <p className="mt-5 text-sm text-zinc-600">
            Fix: open a terminal in the project folder and run <code className="rounded bg-zinc-100 px-1.5 py-0.5">Rscript build_report.R</code>, then reload.
          </p>
        </div>
      </main>
    );
  }

  const { data } = result;
  const { summary, qa } = data;
  const required = summary.figures.filter((f) => f.required);

  const figureChapters: FigureChapter[] = required.map((f) => {
    const size = data.figureSizes[f.id] ?? { width: 1800, height: 1200 };
    return {
      id: f.id,
      number: f.number,
      title: f.title,
      type: f.type,
      purpose: f.purpose,
      interpretation: f.interpretation,
      exists: f.file_exists,
      src: assetUrl(f.file, data.version),
      width: size.width,
      height: size.height,
    };
  });

  // Explorer flags come straight from R's outlier and regression-diagnostic results
  const outlierFlags: Record<string, string[]> = {};
  for (const v of summary.outliers.variables) {
    for (const c of v.countries) (outlierFlags[c.country] ??= []).push(prettyVariable(v.variable));
  }

  return (
    <>
      <a href="#main" className="skip-link">
        Skip to content
      </a>
      <ChapterNav reportAvailable={data.reportAvailable} />
      <main id="main">
        <Hero
          question={summary.project.question}
          reportAvailable={data.reportAvailable}
          qa={{ status: qa.status, pass: qa.counts.pass, total: qa.counts.total }}
          metrics={[
            { value: summary.dataset.observations, label: "cleaned observations", note: "countries" },
            { value: summary.dataset.variables, label: "cleaned variables", note: `${summary.dataset.numeric_variables} numeric` },
            { value: summary.dataset.indicators, label: "World Bank indicators", note: `data year ${summary.project.data_year}` },
            { value: required.length, label: "required visualisations", note: `+ ${summary.figures.length - required.length} diagnostic` },
          ]}
        />
        <ShortAnswer summary={summary} />
        <Pipeline data={data} />
        <KeyIndicators data={data} />
        <Figures figures={figureChapters} />
        <Relationship data={data} />
        <Groups summary={summary} />
        <Robustness summary={summary} />
        <CountryExplorer
          countries={data.countries}
          regions={summary.group_analysis.by_region.map((r) => r.region).sort()}
          incomeLevels={summary.group_analysis.by_income.map((r) => r.income_level)}
          outlierFlags={outlierFlags}
          influential={summary.regression.diagnostics.influential.map((i) => i.country)}
        />
        <DataQuality qa={qa} />
        <Methodology summary={summary} manifest={data.manifest} />
        <SectionA summary={summary} />
        <Limitations limitations={summary.limitations} />
        <Closing reportAvailable={data.reportAvailable} countries={summary.dataset.observations} figures={summary.figures.length} />
        <Reproducibility summary={summary} manifest={data.manifest} reportAvailable={data.reportAvailable} />
      </main>
      <Footer generatedAt={summary.generated_at} source={summary.project.source} />
    </>
  );
}
